import { Job } from "./types";
export const jobs: Job[] = [
  {
    id: 1,
    position: "Software Engineer",
    company: "Tech Solutions Inc.",
    jobType: "Full-time",
    workType: "Remote",
    industry: "Technology",
    experience: "entry-level",
    description: {
      responsibility: "Develop and maintain web applications.",
      qualification: "Bachelor's degree in Computer Science or related field.",
      benefits: "Health insurance, 401(k), remote work options.",
      aboutCompany:
        "Tech Solutions Inc. is a leading provider of innovative tech solutions.",
    },
    salary: "$85,000 - $100,000",
    logo: "tech-solutions-inc-logo.png",
    location: "New York, NY",
    deadline: "2024-08-30",
  },
  {
    id: 2,
    position: "Data Analyst",
    company: "DataCorp",
    jobType: "Full-time",
    workType: "Hybrid",
    industry: "Finance",
    experience: "senior",
    description: {
      responsibility: "Analyze large data sets to identify trends.",
      qualification: "Proficiency in SQL and Python.",
      benefits: "Stock options, flexible work hours.",
      aboutCompany:
        "DataCorp is a financial analytics company providing data-driven insights.",
    },
    salary: "$70,000 - $90,000",
    logo: "datacorp-logo.png",
    location: "San Francisco, CA",
    deadline: "2024-09-10",
  },
  {
    id: 3,
    position: "Marketing Manager",
    company: "Creative Agency",
    jobType: "Full-time",
    workType: "Onsite",
    industry: "Marketing",
    experience: "5+ years",
    description: {
      responsibility: "Lead marketing campaigns and strategies.",
      qualification: "5+ years of marketing experience.",
      benefits: "Health insurance, paid time off.",
      aboutCompany:
        "Creative Agency is a full-service marketing firm specializing in digital marketing.",
    },
    salary: "$75,000 - $95,000",
    logo: "creative-agency-logo.png",
    location: "Los Angeles, CA",
    deadline: "2024-09-15",
  },
  {
    id: 4,
    position: "Product Manager",
    company: "InnovateX",
    jobType: "Full-time",
    workType: "Hybrid",
    industry: "Technology",
    experience: "4+ years",
    description: {
      responsibility: "Oversee product development from ideation to launch.",
      qualification: "Experience in agile methodologies.",
      benefits: "Gym membership, professional development.",
      aboutCompany:
        "InnovateX is a cutting-edge tech company focused on product innovation.",
    },
    salary: "$90,000 - $110,000",
    logo: "innovatex-logo.png",
    location: "Austin, TX",
    deadline: "2024-08-25",
  },
  {
    id: 5,
    position: "Graphic Designer",
    company: "DesignHub",
    jobType: "Contract",
    workType: "Remote",
    industry: "Design",
    experience: "3+ years",
    description: {
      responsibility: "Create visual content for various platforms.",
      qualification: "Proficiency in Adobe Creative Suite.",
      benefits: "Remote work, flexible schedule.",
      aboutCompany:
        "DesignHub is a creative studio specializing in graphic design and branding.",
    },
    salary: "$60,000 - $75,000",
    logo: "designhub-logo.png",
    location: "Seattle, WA",
    deadline: "2024-09-05",
  },
  {
    id: 6,
    position: "Sales Representative",
    company: "SalesPros",
    jobType: "Full-time",
    workType: "Onsite",
    industry: "Sales",
    experience: "entry-level",
    description: {
      responsibility: "Manage client relationships and drive sales.",
      qualification: "Strong communication and negotiation skills.",
      benefits: "Commission, travel opportunities.",
      aboutCompany:
        "SalesPros is a leading sales consultancy firm with a global reach.",
    },
    salary: "$50,000 - $70,000",
    logo: "salespros-logo.png",
    location: "Chicago, IL",
    deadline: "2024-08-28",
  },
  {
    id: 7,
    position: "HR Specialist",
    company: "PeopleFirst",
    jobType: "Full-time",
    workType: "Hybrid",
    industry: "Human Resources",
    experience: "3+ years",
    description: {
      responsibility: "Manage recruitment and employee relations.",
      qualification: "Experience in HR practices and procedures.",
      benefits: "Health and dental insurance, 401(k).",
      aboutCompany:
        "PeopleFirst is an HR solutions provider focusing on employee engagement.",
    },
    salary: "$65,000 - $80,000",
    logo: "peoplefirst-logo.png",
    location: "Atlanta, GA",
    deadline: "2024-09-20",
  },
  {
    id: 8,
    position: "Customer Support Specialist",
    company: "HelpDeskCo",
    jobType: "Part-time",
    workType: "Remote",
    industry: "Customer Service",
    experience: "1+ year",
    description: {
      responsibility: "Provide customer support via phone and email.",
      qualification: "Strong problem-solving skills.",
      benefits: "Work from home, health insurance.",
      aboutCompany:
        "HelpDeskCo is a customer support service provider with a focus on tech support.",
    },
    salary: "$40,000 - $55,000",
    logo: "helpdeskco-logo.png",
    location: "Remote",
    deadline: "2024-08-31",
  },
  {
    id: 9,
    position: "UX/UI Designer",
    company: "CreativeTech",
    jobType: "Contract",
    workType: "Remote",
    industry: "Technology",
    experience: "3+ years",
    description: {
      responsibility:
        "Design user interfaces and experiences for web and mobile.",
      qualification: "Experience with Figma or Sketch.",
      benefits: "Flexible working hours, remote work options.",
      aboutCompany:
        "CreativeTech is a design and technology firm specializing in digital experiences.",
    },
    salary: "$70,000 - $90,000",
    logo: "creativetech-logo.png",
    location: "Boston, MA",
    deadline: "2024-09-12",
  },
  {
    id: 10,
    position: "Project Manager",
    company: "BuildIt",
    jobType: "Full-time",
    workType: "Onsite",
    industry: "Construction",
    experience: "5+ years",
    description: {
      responsibility: "Coordinate and manage construction projects.",
      qualification: "PMP certification preferred.",
      benefits: "Company vehicle, health insurance.",
      aboutCompany:
        "BuildIt is a construction company known for delivering high-quality projects.",
    },
    salary: "$85,000 - $105,000",
    logo: "buildit-logo.png",
    location: "Denver, CO",
    deadline: "2024-08-22",
  },
  {
    id: 11,
    position: "Content Writer",
    company: "WriteNow",
    jobType: "Contract",
    workType: "Remote",
    industry: "Content Creation",
    experience: "entry-level",
    description: {
      responsibility: "Create and edit content for blogs and websites.",
      qualification: "Strong writing and editing skills.",
      benefits: "Remote work, flexible schedule.",
      aboutCompany:
        "WriteNow is a content creation company specializing in digital content.",
    },
    salary: "$50,000 - $65,000",
    logo: "writenow-logo.png",
    location: "Remote",
    deadline: "2024-09-07",
  },
  {
    id: 12,
    position: "Financial Analyst",
    company: "FinancePro",
    jobType: "Full-time",
    workType: "Hybrid",
    industry: "Finance",
    experience: "3+ years",
    description: {
      responsibility: "Analyze financial data and create reports.",
      qualification: "Bachelor's degree in Finance or related field.",
      benefits: "401(k), health insurance.",
      aboutCompany:
        "FinancePro is a financial services company focused on investment analysis.",
    },
    salary: "$75,000 - $90,000",
    logo: "financepro-logo.png",
    location: "New York, NY",
    deadline: "2024-08-29",
  },
  {
    id: 13,
    position: "Operations Manager",
    company: "LogiCo",
    jobType: "Full-time",
    workType: "Onsite",
    industry: "Logistics",
    experience: "4+ years",
    description: {
      responsibility: "Oversee daily operations and logistics.",
      qualification: "Experience in operations management.",
      benefits: "Company car, health insurance.",
      aboutCompany:
        "LogiCo is a logistics company providing supply chain solutions.",
    },
    salary: "$80,000 - $100,000",
    logo: "logico-logo.png",
    location: "Miami, FL",
    deadline: "2024-09-18",
  },
  {
    id: 14,
    position: "DevOps Engineer",
    company: "CloudNet",
    jobType: "Full-time",
    workType: "Remote",
    industry: "Technology",
    experience: "3+ years",
    description: {
      responsibility: "Manage cloud infrastructure and CI/CD pipelines.",
      qualification: "Experience with AWS or Azure.",
      benefits: "Stock options, health insurance.",
      aboutCompany:
        "CloudNet is a cloud services provider offering scalable infrastructure solutions.",
    },
    salary: "$95,000 - $120,000",
    logo: "cloudnet-logo.png",
    location: "Remote",
    deadline: "2024-09-22",
  },
  {
    id: 15,
    position: "Mechanical Engineer",
    company: "EngineersPlus",
    jobType: "Full-time",
    workType: "Onsite",
    industry: "Engineering",
    experience: "entry-level",
    description: {
      responsibility: "Design and test mechanical systems.",
      qualification: "Bachelor's degree in Mechanical Engineering.",
      benefits: "Health insurance, retirement plans.",
      aboutCompany: "EngineersPlus is a multidisciplinary engineering firm.",
    },
    salary: "$85,000 - $100,000",
    logo: "engineersplus-logo.png",
    location: "Houston, TX",
    deadline: "2024-09-10",
  },
  {
    id: 16,
    position: "Cybersecurity Specialist",
    company: "SecureTech",
    jobType: "Full-time",
    workType: "Hybrid",
    industry: "Technology",
    experience: "4+ years",
    description: {
      responsibility: "Implement and monitor cybersecurity measures.",
      qualification: "Experience with network security.",
      benefits: "Health insurance, paid time off.",
      aboutCompany:
        "SecureTech is a cybersecurity firm dedicated to protecting digital assets.",
    },
    salary: "$100,000 - $130,000",
    logo: "securetech-logo.png",
    location: "Washington, DC",
    deadline: "2024-08-30",
  },
  {
    id: 17,
    position: "Business Analyst",
    company: "BizSolutions",
    jobType: "Full-time",
    workType: "Remote",
    industry: "Consulting",
    experience: "3+ years",
    description: {
      responsibility: "Analyze business processes and recommend improvements.",
      qualification: "Strong analytical and problem-solving skills.",
      benefits: "401(k), flexible work hours.",
      aboutCompany:
        "BizSolutions is a consulting firm helping businesses optimize their operations.",
    },
    salary: "$70,000 - $85,000",
    logo: "bizsolutions-logo.png",
    location: "Philadelphia, PA",
    deadline: "2024-09-14",
  },
  {
    id: 18,
    position: "IT Support Specialist",
    company: "TechAssist",
    jobType: "Part-time",
    workType: "Onsite",
    industry: "Information Technology",
    experience: "2+ years",
    description: {
      responsibility: "Provide technical support and troubleshooting.",
      qualification: "Experience with Windows and Mac OS.",
      benefits: "Flexible schedule, paid training.",
      aboutCompany:
        "TechAssist is an IT support company providing onsite technical services.",
    },
    salary: "$45,000 - $55,000",
    logo: "techassist-logo.png",
    location: "Portland, OR",
    deadline: "2024-09-03",
  },
  {
    id: 19,
    position: "Sales Manager",
    company: "RetailCorp",
    jobType: "Full-time",
    workType: "Onsite",
    industry: "Retail",
    experience: "5+ years",
    description: {
      responsibility: "Manage sales teams and develop sales strategies.",
      qualification: "Proven track record in sales management.",
      benefits: "Commission, health insurance.",
      aboutCompany:
        "RetailCorp is a retail company with a focus on consumer electronics.",
    },
    salary: "$80,000 - $100,000",
    logo: "retailcorp-logo.png",
    location: "Dallas, TX",
    deadline: "2024-09-16",
  },
  {
    id: 20,
    position: "Legal Assistant",
    company: "LawFirmCo",
    jobType: "Part-time",
    workType: "Onsite",
    industry: "Legal",
    experience: "2+ years",
    description: {
      responsibility: "Assist attorneys with legal research and documentation.",
      qualification: "Paralegal certification preferred.",
      benefits: "Flexible schedule, professional development.",
      aboutCompany: "LawFirmCo is a law firm specializing in corporate law.",
    },
    salary: "$50,000 - $65,000",
    logo: "lawfirmco-logo.png",
    location: "New York, NY",
    deadline: "2024-08-27",
  },
  {
    id: 21,
    position: "Operations Analyst",
    company: "OperationsInc",
    jobType: "Full-time",
    workType: "Remote",
    industry: "Consulting",
    experience: "2+ years",
    description: {
      responsibility: "Analyze and improve operational processes.",
      qualification: "Experience with data analysis tools.",
      benefits: "Remote work, health insurance.",
      aboutCompany:
        "OperationsInc is a consulting firm specializing in operational efficiency.",
    },
    salary: "$65,000 - $80,000",
    logo: "operationsinc-logo.png",
    location: "Remote",
    deadline: "2024-09-11",
  },
];
