export const styles = {
  background: {
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundImage: "linear-gradient(135deg, #72EDF2 10%, #5151E5 100%)",
    padding: "0",
  },
  container: {
    height: "auto",
    width: "90%",
    maxWidth: "500px",
    textAlign: "center",
    backgroundColor: "#fff",
    boxShadow: "0px 4px 15px rgba(0, 0, 0, 0.2)",
    borderRadius: "12px",
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    margin: "0 auto",
  },
  title: {
    marginBottom: "20px",
    fontWeight: 700,
    color: "#333",
    fontFamily: "'Poppins', sans-serif",
    fontSize: "1.5rem",
  },
  googleButton: {
    backgroundColor: "#fff",
    borderColor: "#ccc",
    color: "#555",
    marginBottom: "20px",
    borderRadius: "50px",
    padding: "10px",
    fontSize: "0.9rem",
    width: "80%",
  },
  divider: {
    margin: "20px 0",
    color: "#999",
    fontWeight: 500,
    fontSize: "0.8rem",
    width: "80%",
  },
  input: {
    marginBottom: "15px",
    borderRadius: "50px",
    fontSize: "0.9rem",
    width: "80%",
  },
  submitButton: {
    marginTop: "20px",
    padding: "12px",
    fontWeight: 700,
    fontSize: "1rem",
    backgroundImage: "linear-gradient(90deg, #28a745 0%, #28a745 100%)",
    borderRadius: "50px",
    color: "#fff",
    width: "80%",
  },
  toggleText: {
    marginTop: "20px",
    color: "#666",
    fontFamily: "'Roboto', sans-serif",
    fontSize: "0.8rem",
  },
  toggleButton: {
    textTransform: "none",
    fontWeight: 700,
    marginLeft: "5px",
    fontSize: "0.8rem",
  },
  "@media (max-width: 600px)": {
    container: {
      height: "100vh",
      width: "100vw",
      backgroundColor: "#fff",
      boxShadow: "none",
      borderRadius: "0",
      padding: "20px",
      display: "flex",
      flexDirection: "column",
      justifyContent: "center",
      alignItems: "center",
    },
  },
};
